a("<template>");
a("  <div class=\"page-container\">");
a("    <div class=\"page-header\">");
a("      <h2>配置下发管理</h2>");
a("      <p class=\"page-desc\">统一管理各模块配置，开启后将覆盖租户本地设置</p>");
a("    </div>");
a("");
a("    <el-alert v-if=\"saveSuccess\" title=\"配置已保存并下发\" type=\"success\" show-icon :closable=\"true\" style=\"margin-bottom:16px\" />");
a("");
a("    <el-collapse v-model=\"activeModules\">");