const fs = require('fs');
const p = require('path');
const dst = p.join(__dirname, 'src', 'views', 'modules', 'Distribute.vue');
const Q = String.fromCharCode(34);
const NL = String.fromCharCode(10);
const t = [];
const a = (s) => t.push(s);
const b = () => t.push('');
a('<template>');
a('  <div class=' + Q + 'page-container' + Q + '>');
a('    <div class=' + Q + 'page-header' + Q + '>');
a('      <h2>\u914D\u7F6E\u4E0B\u53D1\u7BA1\u7406</h2>');
a('      <p class=' + Q + 'page-desc' + Q + '>\u7EDF\u4E00\u7BA1\u7406\u5404\u6A21\u5757\u914D\u7F6E\uFF0C\u5F00\u542F\u540E\u5C06\u8986\u76D6\u79DF\u6237\u672C\u5730\u8BBE\u7F6E</p>');
a('    </div>');
b();
a('    <el-alert v-if=' + Q + 'saveSuccess' + Q + ' title=' + Q + '\u914D\u7F6E\u5DF2\u4FDD\u5B58\u5E76\u4E0B\u53D1' + Q + ' type=' + Q + 'success' + Q + ' show-icon :closable=' + Q + 'true' + Q + ' style=' + Q + 'margin-bottom:16px' + Q + ' />');
b();
a('    <el-collapse v-model=' + Q + 'activeModules' + Q + '>');
fs.writeFileSync('_gen.cjs', t.map(l => 'a(' + JSON.stringify(l) + ');').join(NL) , 'utf8');
console.log('init done', t.length, 'lines');
